### PR TITLE
fix!: debian builds to use correct context & dockerfile

### LINKED ISSUE #88: Debian builds actually based upon Alpine
I was experiencing an issue similar #68, getting TLS to work with MQTT. I'd previously had issues with the Alpine container and had switched to the Debian-based builds to get everything working. The [issue linked](https://github.com/merbanan/rtl_433/issues/1569#issuecomment-1446117444) to by @metrafonic had a few hints on checking the SSL library, which I tried to double checked only to find that `apt` was missing from the Debian builds. Doing a sanity check revealed the `*-debian-*` images are actually based on Alpine:

```bash
user@hostname:/path$ docker run --rm -it --entrypoint /bin/sh ghcr.io/hertzg/rtl_433_docker:22.11-debian-bullseye
Unable to find image 'ghcr.io/hertzg/rtl_433_docker:22.11-debian-bullseye' locally
22.11-debian-bullseye: Pulling from hertzg/rtl_433_docker
7264a8db6415: Already exists 
1bbc95af9f57: Pull complete 
4f4fb700ef54: Pull complete 
41f9d701da10: Pull complete 
Digest: sha256:3c1c545a350b71cbf84804ba97719372c5e460ff5374ef899d084834f4c73f67
Status: Downloaded newer image for ghcr.io/hertzg/rtl_433_docker:22.11-debian-bullseye
~ # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.3
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
~ # 
```

The current tags for `22.11-debian-bullseye`[^1] and `22.11-debian-bookworm`[^2] likewise share the base layer `4693057ce2364720d39e57e85a5b8e0bd9ac3573716237736d6470ec5b7b7230`, which is an Alpine base.

[^1]: `ghcr.io/hertzg/rtl_433_docker@sha256:3c1c545a350b71cbf84804ba97719372c5e460ff5374ef899d084834f4c73f67`
[^2]: `ghcr.io/hertzg/rtl_433_docker@sha256:75c23722d3b83748ab1d581db5b2f94b4657ec55f4b3652b2f349e3d18acf96a`

A [recent GitHub action log](https://github.com/hertzg/rtl_433_docker/actions/runs/6031332849/job/16364853558) also indicates that the Alpine configuration is being pulled at runtime to build the `*-debian-*` images:

image

I'm not familiar with TypeScript or the build process used by the project, but I *think* the offending lines were introduced in 62d7991, meaning all the builds since May have been based on the wrong image. I think this could help explain some other recent issues, like #83.

https://github.com/hertzg/rtl_433_docker/blob/cf023df8f811ff7553e474fe4f949e790e80bc04/src/debian.config.ts#L78-L79

I can submit a PR just changing those lines, but without being more familiar with the build system I'm not sure if I can accurately test it.

### PR DESCRIPTION
**Pull request by hertzg**
fixes #88

### CODE REVIEW

**Comment by ravngr** [comment]
@hertzg Bet you're swimming in actions notifications 😅

Had a look at the offending build line, on a bare-metal Debian 12/bookworm install I can't find matches for:
- `'^libsoapysdr0\\.[6-7]$'`: `libsoapysdr0.8/stable 0.8.1-3` is current
- `libssl1.1`: `libssl3` seems like a jump...
- '^soapysdr0\\.[6-7]-module-all$': `soapysdr0.8-module-all` is current

**Comment by ravngr** [comment]
Pinning could be another option, I think you can restrict that to a specific source. Looks like you tweaked it already 👌

Side question: is there a way to pull the generated images when generated inside a PR/check/review?

**Comment by hertzg** [comment]
> Side question: is there a way to pull the images when generated inside a PR/check/review?

Unfortunately no, didn't have time to tweak the build system to that level yet (definitely doable), the PR's are just built and stored in cache (github cache).

**Comment by hertzg** [comment]
Ok so seems like `19.08` & `18.12` have build issues on `bookworm`, most likely due to the newer dependencies. Since they are tags there's no way to fix that even in upstream without rewriting history so I'll be skipping them from build. 🤷‍♂️

**Pull request merged**
